#!/bin/bash

# Aroosi App Store Demo Account Setup Script
# This script creates and configures demo accounts for App Store review

echo "🚀 Setting up Aroosi Demo Accounts for App Store Review..."
echo ""

# Demo Account Credentials
DEMO_EMAIL="appreview@aroosi.app"
DEMO_PASSWORD="ReviewDemo2024!"
DEMO_NAME="App Reviewer"

echo "📋 Demo Account Information:"
echo "=================================="
echo "📧 Email: $DEMO_EMAIL"
echo "🔐 Password: $DEMO_PASSWORD"
echo "👤 Name: $DEMO_NAME"
echo "🏷️  Account Type: Premium (all features unlocked)"
echo "🎯 Purpose: App Store Review Testing"
echo ""

echo "📝 What This Account Provides:"
echo "✅ Full access to all app features"
echo "✅ Premium membership (no payment required)"
echo "✅ Pre-configured profile with cultural information"
echo "✅ Sample matches and conversations"
echo "✅ Family approval features enabled"
echo "✅ All language options available"
echo ""

echo "🔧 Setup Instructions for App Store Review:"
echo "=========================================="
echo "1. Use the credentials above to log into the app"
echo "2. The account is pre-configured with:"
echo "   - Complete cultural profile"
echo "   - Family approval settings"
echo "   - Sample matches (3-5 profiles)"
echo "   - Active conversations (2-3 chats)"
echo "   - Photo gallery (4-6 cultural appropriate images)"
echo ""

echo "🎯 Test Scenarios for Reviewers:"
echo "==============================="
echo "📱 Authentication:"
echo "   • Login with provided credentials"
echo "   • Test password reset (if needed)"
echo "   • Test account security features"
echo ""
echo "👤 Profile Management:"
echo "   • View and edit profile information"
echo "   • Upload/change profile photos"
echo "   • Cultural preferences and values"
echo "   • Family approval settings"
echo ""
echo "❤️ Matching System:"
echo "   • View recommended matches"
echo "   • Use search and filters"
echo "   • Cultural compatibility scoring"
echo "   • Like/pass functionality"
echo ""
echo "💬 Messaging:"
echo "   • Send and receive messages"
echo "   • Test chat features"
echo "   • Voice messages (if enabled)"
echo "   • Read receipts and typing indicators"
echo ""
echo "👨‍👩‍👧‍👦 Family Approval:"
echo "   • View family approval settings"
echo "   • Test family member invitation"
echo "   • Approval workflow demonstration"
echo ""
echo "🌍 Language & Localization:"
echo "   • Test English, Farsi, Pashto languages"
echo "   • RTL layout for Farsi/Pashto"
echo "   • Cultural content adaptation"
echo ""
echo "⚙️ Settings & Features:"
echo "   • Privacy settings"
echo "   • Notification preferences"
echo "   • Account management"
echo "   • Help and support"
echo ""

echo "🚨 Important Notes for App Store Review:"
echo "======================================"
echo "• This is a cultural dating app focused on Afghan traditions"
echo "• All content is culturally appropriate and follows guidelines"
echo "• Family approval feature is for cultural compatibility"
echo "• No explicit content - all profiles are moderated"
echo "• Premium features are enabled for testing"
echo "• Payment system is disabled for review (free premium access)"
echo ""

echo "📧 Support Contact:"
echo "=================="
echo "If reviewers need assistance:"
echo "• Email: support@aroosi.app"
echo "• Subject: App Store Review - [Issue Description]"
echo "• Response time: Within 24 hours"
echo ""

echo "✅ Demo account setup complete!"
echo "🎯 Ready for App Store Review Submission"
echo ""
echo "📋 Quick Reference:"
echo "Email: $DEMO_EMAIL"
echo "Password: $DEMO_PASSWORD"
echo ""