name: Store Listings

on:
  workflow_dispatch:
  push:
    paths:
      - 'fastlane/metadata/**'
      - 'ios/fastlane/**'
      - 'android/fastlane/**'

jobs:
  upload:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install fastlane
        run: |
          gem install fastlane -NV

      - name: iOS - Prepare API key
        if: ${{ secrets.APPSTORE_API_KEY_P8 != '' }}
        working-directory: ios/fastlane
        run: |
          echo "${APPSTORE_API_KEY_P8}" > api_key.p8
        env:
          APPSTORE_API_KEY_P8: ${{ secrets.APPSTORE_API_KEY_P8 }}

      - name: iOS - Upload metadata
        if: ${{ secrets.APPSTORE_API_KEY_ID != '' && secrets.APPSTORE_API_ISSUER_ID != '' && secrets.APPSTORE_API_KEY_P8 != '' }}
        working-directory: ios
        env:
          IOS_APP_IDENTIFIER: ${{ secrets.IOS_APP_IDENTIFIER }}
          APPSTORE_API_KEY_ID: ${{ secrets.APPSTORE_API_KEY_ID }}
          APPSTORE_API_ISSUER_ID: ${{ secrets.APPSTORE_API_ISSUER_ID }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPSTORE_TEAM_ID: ${{ secrets.APPSTORE_TEAM_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        run: |
          fastlane upload_metadata

      - name: Android - Upload metadata
        if: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON != '' }}
        working-directory: android
        env:
          ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
          GOOGLE_PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        run: |
          fastlane upload_metadata
